const ActionType = {
    ADD_NEW_USER: 'ADD_NEW_USER',
    SHOW_USERS: 'SHOW_USERS',
    SHOW_ADDRESS: 'SHOW_ADDRESS',
    SHOW_COMPANY: 'SHOW_COMPANY',
    ADD_ADDRESS: 'ADD_ADDRESS',
    ADD_COMPANY: 'ADD_COMPANY'
}
export default ActionType;
